YOLO_file_location: C:\\Users\\ianki\\Documents\\2023-2024_coding\\AI_studies\\starfish_final\\last_ckpt.pt
img_size: 640
conf_thres: 0.2
iou_thres: 0.45
max_det: 1000
device: 0
agnostic_nms: False
half: False
yolo_conf_threshold: 0.31
video_file: C:\\Users\\ianki\\Documents\\2023-2024_coding\\AI_studies\\starfish_final\\seafloor_footage.avi
output_file_location: C:\\Users\\ianki\\Documents\\2023-2024_coding\\AI_studies\\starfish_final\\starfish_finder.avi
overlap_threshold: 50
csv_filepath: C:\\Users\\ianki\\Documents\\2023-2024_coding\\AI_studies\\starfish_final\\starfish_bboxes.csv
faster_rcnn_conf_threshold: 0.5
frame_rate_of_program: 30
faster_rcnn_location: C:\\Users\\ianki\\Documents\\2023-2024_coding\\AI_studies\\starfish_final\\best_brittle_star_model7.pth